Fix Python 3.8 incompatibility (bug in trio_asyncio with postgresql)
